In [ ]:
from keras.layers import Input
from keras.layers import concatenate
from keras.models import Model
from keras.layers import Dense
#from keras.layers import *
import tensorflow as tf
tf.random.set_seed(34)

inputs = Input(shape=2)
h1_1 = Dense(units = 2, activation = 'relu')(inputs)
h1_2 = Dense(units = 2, activation = 'relu')(inputs)
c = concatenate([h1_1, h1_2])
h2 = Dense(units = 2, activation= 'relu')(c)
o = Dense(units = 1, activation = 'sigmoid')(h2)
functional_model = Model(inputs,o)
functional_model.summary()

Model: "model_11"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_14 (InputLayer)          [(None, 2)]          0           []                               
                                                                                                  
 dense_49 (Dense)               (None, 2)            6           ['input_14[0][0]']               
                                                                                                  
 dense_50 (Dense)               (None, 2)            6           ['input_14[0][0]']               
                                                                                                  
 concatenate_12 (Concatenate)   (None, 4)            0           ['dense_49[0][0]',               
                                                                  'dense_50[0][0]']        

In [ ]:
#model for or gate
import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [ ]:
functional_model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
functional_model.fit(X, Y, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 9ms/step - loss: 0.2482 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 0.2477 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 0.2472 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.2468 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 0.2463 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.2460 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 0.2455 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.2451 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.2446 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.2443 - accuracy: 1.0000


In [ ]:
loss, accuracy = functional_model.evaluate(X,Y)

1/1 [==============================] - 0s 25ms/step - loss: 0.2438 - accuracy: 1.0000


In [ ]:
pred = functional_model.predict(X)
#pred = (functional_model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 67ms/step


array([[0.49810112],
       [0.9513967 ],
       [0.8069379 ],
       [0.978768  ]], dtype=float32)

In [ ]:
functional_model.layers

In [ ]:
hidden1 = functional_model.layers[1]
weights, biases = hidden1.get_weights()
print("weights: " , weights)
print("\n")
print("biases: " , biases)

weights:  [[-0.06758756 -0.5860491 ]
 [ 1.1027528   0.46501186]]


biases:  [ 8.6478743e-05 -8.8222197e-04]


In [ ]:
output = functional_model.layers[-1]
weights, biases = output.get_weights()
print("weights: " , weights)
print("\n")
print("biases: " , biases)

weights:  [[-0.28995466]
 [ 1.4268916 ]]


biases:  [-0.0074116]


In [ ]:
#we get all the weights and biases
functional_model.get_weights()

[array([[-0.06758756, -0.5860491 ],
        [ 1.1027528 ,  0.46501186]], dtype=float32),
 array([ 8.6478743e-05, -8.8222197e-04], dtype=float32),
 array([[-1.0973021 ,  1.1883938 ],
        [ 0.02335433,  1.0731537 ]], dtype=float32),
 array([-9.1656880e-04,  8.2977465e-05], dtype=float32),
 array([[ 0.5353694 ,  0.85484487],
        [ 0.25732407,  0.7849635 ],
        [-0.4667278 ,  0.6611753 ],
        [ 0.8239594 ,  1.0154114 ]], dtype=float32),
 array([0.00181498, 0.00010502], dtype=float32),
 array([[-0.28995466],
        [ 1.4268916 ]], dtype=float32),
 array([-0.0074116], dtype=float32)]