In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 2)                 6         
                                                                 
 dense_4 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(4,input_dim=3,activation='relu'))
model.add(Dense(2,activation='sigmoid'))
model.add(Dense(1,activation='relu'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 4)                 16        
                                                                 
 dense_3 (Dense)             (None, 2)                 10        
                                                                 
 dense_4 (Dense)             (None, 1)                 3         
                                                                 
Total params: 29
Trainable params: 29
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(3,input_dim=2,activation='sigmoid'))
model.add(Dense(1,activation='relu'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 3)                 9         
                                                                 
 dense_12 (Dense)            (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#train model for or gate
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [ ]:
model.fit(X,Y,epochs=2000, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, Y)

1/1 [==============================] - 0s 89ms/step - loss: 0.1031 - accuracy: 1.0000


In [ ]:
pred = model.predict(X)
pred = (model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 13ms/step


array([[0],
       [1],
       [1],
       [1]])

In [ ]:
#model to train and gate
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])

In [ ]:
history = model.fit(X,Y,epochs=2500, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, Y)

1/1 [==============================] - 0s 16ms/step - loss: 0.0347 - accuracy: 1.0000


In [ ]:
pred = model.predict(X)
pred = (model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 16ms/step


array([[0],
       [0],
       [0],
       [1]])

In [ ]:
#Model for xor
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(2,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])

In [ ]:
history = model.fit(X,Y,epochs=10000, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, Y)

1/1 [==============================] - 0s 116ms/step - loss: 0.0243 - accuracy: 1.0000


In [ ]:
pred = model.predict(X)
pred = (model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 16ms/step


array([[0],
       [1],
       [1],
       [0]])