In [ ]:
from keras.layers import Input
from keras.layers import concatenate
from keras.models import Model
from keras.layers import Dense
#from keras.layers import *
import tensorflow as tf
import keras
tf.random.set_seed(34)

inputs = Input(shape=2)
h1_1 = Dense(units = 2, activation = 'relu')(inputs)
h1_2 = Dense(units = 2, activation = 'relu')(inputs)
c = concatenate([h1_1, h1_2])
h2 = Dense(units = 2, activation= 'relu')(c)
o = Dense(units = 1, activation = 'sigmoid')(h2)
functional_model = Model(inputs,o)
functional_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 2)]          0           []                               
                                                                                                  
 dense_8 (Dense)                (None, 2)            6           ['input_3[0][0]']                
                                                                                                  
 dense_9 (Dense)                (None, 2)            6           ['input_3[0][0]']                
                                                                                                  
 concatenate_2 (Concatenate)    (None, 4)            0           ['dense_8[0][0]',                
                                                                  'dense_9[0][0]']          

In [ ]:
functional_model.layers[0].get_weights()

[]

In [ ]:
len(functional_model.layers)

6

In [ ]:
functional_model.layers[1].get_weights()

[array([[-0.06836784, -0.5860491 ],
        [ 1.1002396 ,  0.46330345]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [ ]:
functional_model.layers[2].get_weights()

[array([[-1.0973021 ,  1.179897  ],
        [ 0.02158129,  1.0703229 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [ ]:
functional_model.layers[-1].get_weights()

[array([[-0.3006308],
        [ 1.4129516]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
#How to use or set weights
#functional_model.layers[0].set_weights(given_weights)
#given_weights is the variable

In [ ]:
#model for or gate
import numpy as np
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[1]])

In [ ]:
functional_model.get_weights()

[array([[-0.06836784, -0.5860491 ],
        [ 1.1002396 ,  0.46330345]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0973021 ,  1.179897  ],
        [ 0.02158129,  1.0703229 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.5361321 ,  0.8511841 ],
        [ 0.25754976,  0.78388   ],
        [-0.46671724,  0.66112447],
        [ 0.8272252 ,  0.9997351 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.3006308],
        [ 1.4129516]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
functional_model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
my_callback = keras.callbacks.EarlyStopping(monitor = 'loss', mode = 'min', patience = 5, min_delta = 0.001)

In [ ]:
functional_model.get_weights()

[array([[-0.06836784, -0.5860491 ],
        [ 1.1002396 ,  0.46330345]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0973021 ,  1.179897  ],
        [ 0.02158129,  1.0703229 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.5361321 ,  0.8511841 ],
        [ 0.25754976,  0.78388   ],
        [-0.46671724,  0.66112447],
        [ 0.8272252 ,  0.9997351 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.3006308],
        [ 1.4129516]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
functional_model.fit(X, Y, epochs=10000, callbacks=my_callback, verbose=0)


In [ ]:
loss, accuracy = functional_model.evaluate(X,Y)

1/1 [==============================] - 0s 162ms/step - loss: 0.1928 - accuracy: 1.0000


In [ ]:
pred = functional_model.predict(X)
#pred = (functional_model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 80ms/step


array([[0.4636814],
       [0.978118 ],
       [0.8860612],
       [0.9950164]], dtype=float32)

In [ ]:
functional_model.layers

In [ ]:
hidden1 = functional_model.layers[1]
weights, biases = hidden1.get_weights()
print("weights: " , weights)
print("\n")
print("biases: " , biases)

weights:  [[-0.06198551 -0.5860491 ]
 [ 1.125425    0.48129252]]


biases:  [-2.5602407e-05 -4.6890025e-04]


In [ ]:
output = functional_model.layers[-1]
weights, biases = output.get_weights()
print("weights: " , weights)
print("\n")
print("biases: " , biases)

weights:  [[-0.19108441]
 [ 1.5710553 ]]


biases:  [-0.13807876]


In [ ]:
#we get all the weights and biases
functional_model.get_weights()

[array([[-0.06198551, -0.5860491 ],
        [ 1.125425  ,  0.48129252]], dtype=float32),
 array([-2.5602407e-05, -4.6890025e-04], dtype=float32),
 array([[-1.0973021 ,  1.2920595 ],
        [ 0.03937855,  1.1009154 ]], dtype=float32),
 array([-0.00116813,  0.00854856], dtype=float32),
 array([[ 0.53021914,  0.88657314],
        [ 0.25566804,  0.79523677],
        [-0.46683347,  0.66184604],
        [ 0.79781455,  1.1793894 ]], dtype=float32),
 array([ 0.03217831, -0.01034249], dtype=float32),
 array([[-0.19108441],
        [ 1.5710553 ]], dtype=float32),
 array([-0.13807876], dtype=float32)]

In [ ]:
#change weight and bias by adding 0.5 in it
lst = functional_model.get_weights()
for i in range(len(lst)):
  for j in range(len(lst[i])):
    lst[i][j]  = lst[i][j] +0.5
lst

[array([[ 0.43801448, -0.08604908],
        [ 1.625425  ,  0.9812925 ]], dtype=float32),
 array([0.4999744, 0.4995311], dtype=float32),
 array([[-0.5973021,  1.7920595],
        [ 0.5393785,  1.6009154]], dtype=float32),
 array([0.49883187, 0.50854856], dtype=float32),
 array([[1.0302191 , 1.3865731 ],
        [0.75566804, 1.2952368 ],
        [0.03316653, 1.161846  ],
        [1.2978146 , 1.6793894 ]], dtype=float32),
 array([0.5321783 , 0.48965752], dtype=float32),
 array([[0.3089156],
        [2.0710554]], dtype=float32),
 array([0.36192125], dtype=float32)]

In [ ]:
functional_model.set_weights(lst)

In [ ]:
functional_model.get_weights()

[array([[ 0.43801448, -0.08604908],
        [ 1.625425  ,  0.9812925 ]], dtype=float32),
 array([0.4999744, 0.4995311], dtype=float32),
 array([[-0.5973021,  1.7920595],
        [ 0.5393785,  1.6009154]], dtype=float32),
 array([0.49883187, 0.50854856], dtype=float32),
 array([[1.0302191 , 1.3865731 ],
        [0.75566804, 1.2952368 ],
        [0.03316653, 1.161846  ],
        [1.2978146 , 1.6793894 ]], dtype=float32),
 array([0.5321783 , 0.48965752], dtype=float32),
 array([[0.3089156],
        [2.0710554]], dtype=float32),
 array([0.36192125], dtype=float32)]

In [ ]:
#now train the model using new weights
functional_model.compile(optimizer='sgd', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
my_callback = keras.callbacks.EarlyStopping(monitor = 'loss', mode = 'min', patience = 5, min_delta = 0.001)

In [ ]:
functional_model.fit(X, Y, epochs=10000, callbacks=my_callback, verbose=0)

In [ ]:
loss, accuracy = functional_model.evaluate(X,Y)

1/1 [==============================] - 0s 147ms/step - loss: 0.1788 - accuracy: 0.7500


In [ ]:
pred = functional_model.predict(X)
#pred = (functional_model.predict(X)>0.5).astype(int)
pred

1/1 [==============================] - 0s 98ms/step


array([[0.50975066],
       [0.9999886 ],
       [0.9978503 ],
       [0.99999994]], dtype=float32)