In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
b = a.to("cuda:0")
b

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [ ]:
a+a

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [ ]:
#It is not working because both the tensor are on different device
a+b

RuntimeError: ignored

In [ ]:
import tensorflow as tf
st1 = tf.SparseTensor(indices = [[0,1],[1,0],[2,3]], values=[1,2.,3],dense_shape=[3,4])
st1

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(st1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [ ]:
st2 = tf.SparseTensor(indices = [[0,1],[1,0],[2,3]], values=[1,2.,3],dense_shape=[8,9])
tf.sparse.to_dense(st2)

<tf.Tensor: shape=(8, 9), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
st1*42

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([ 42.  84. 126.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(st1*42)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  0.,  42.,   0.,   0.],
       [ 84.,   0.,   0.,   0.],
       [  0.,   0.,   0., 126.]], dtype=float32)>

In [ ]:
tf.sparse.to_dense(st1-20)

TypeError: ignored

In [ ]:
a1 = tf.TensorArray(dtype=tf.float32, size=3) #like list of list or tensor of tensor

In [ ]:
a1 = a1.write(0,tf.constant([1.,2.]))
a1 = a1.write(1,tf.constant([3.,10.]))
a1 = a1.write(2,tf.constant([5.,7.]))

In [ ]:
tensor1 = a1.read(1) #poping operation can not read again because it has been poped out.
tensor1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [ ]:
a1.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

In [ ]:
a1 = a1.write(3,tf.constant([1.,4.]))

OutOfRangeError: ignored

In [ ]:
#Create an dynamic array
a2  = tf.TensorArray(dtype=tf.float32, size=0,dynamic_size = True)
a2 = a2.write(0,tf.constant([1.,2.]))
a2 = a2.write(1,tf.constant([3.,10.]))
a2 = a2.write(2,tf.constant([5.,7.]))
a2 = a2.write(3,tf.constant([1.,4.]))

In [ ]:
ten1 = a2.read(1)

In [ ]:
a2.stack()

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.],
       [1., 4.]], dtype=float32)>

In [ ]:
a3 = tf.TensorArray(dtype=tf.float32, size=0,dynamic_size = True, clear_after_read = False)
a3 = a3.write(0,tf.constant([1.,2.]))
a3 = a3.write(1,tf.constant([3.,10.]))
a3 = a3.write(2,tf.constant([5.,7.]))
a3 = a3.write(3,tf.constant([1.,4.]))

In [ ]:
t1 = a3.read(1) #we can read now multiple time because value is not flush out.

In [ ]:
a3.stack()

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3., 10.],
       [ 5.,  7.],
       [ 1.,  4.]], dtype=float32)>

In [ ]:
tf.constant(b"hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [ ]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [ ]:
u = tf.constant([ord(c) for c in "café"]) #convert it into ascii value
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [ ]:
chr(233)

'é'

In [ ]:
tf.strings.unicode_encode(u,"UTF-8")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [ ]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])
n2


<ipython-input-8-6e492ade1032>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]), list([10, 11])],
      dtype=object)

In [ ]:
#ragged array
'''[[1,2,3,4],
    [5,6],
    [7,8,9],
    [10],
    [11,12,13,14]]'''

In [ ]:
#ragged tensors
r1 = tf.constant([[1.,2,3],[4.,5,6.,7.]])

ValueError: ignored

In [ ]:
r1 = tf.ragged.constant([[65,66],[],[67]])
r1

<tf.RaggedTensor [[65, 66], [], [67]]>

In [ ]:
r2 = tf.ragged.constant([[67,97,102,233],[67,111,102,102,101,101],[99,97,102,102,232],[21654,21857]])
r2

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [21654, 21857]]>

In [ ]:
r3 = tf.concat([r1,r2],axis=0)
r3.shape

TensorShape([7, None])

In [ ]:
r4 = tf.ragged.constant([[1,2],[3,4]])
r5 = tf.ragged.constant([[5,6],[7,8]])
tf.concat([r4,r5],axis=0)

<tf.RaggedTensor [[1, 2],
 [3, 4],
 [5, 6],
 [7, 8]]>

In [ ]:
tf.concat([r4,r5],axis=1)

<tf.RaggedTensor [[1, 2, 5, 6],
 [3, 4, 7, 8]]>

In [ ]:
tf.concat([r1,r2],axis=1)

InvalidArgumentError: ignored

In [ ]:
r4 = tf.ragged.constant([[1,2],[3,4,5]])
r5 = tf.ragged.constant([[6],[7,8,9,10]])
tf.concat([r4,r5],axis=1)

<tf.RaggedTensor [[1, 2, 6], [3, 4, 5, 7, 8, 9, 10]]>

In [ ]:
r6 = tf.ragged.constant([[5,6],[7,8,9,10]])
tf.concat([r4,r6],axis=0)

<tf.RaggedTensor [[1, 2], [3, 4, 5], [5, 6], [7, 8, 9, 10]]>

In [ ]:
tf.concat([r4,r6],axis=1)

<tf.RaggedTensor [[1, 2, 5, 6], [3, 4, 5, 7, 8, 9, 10]]>

In [ ]:
r7=tf.ragged.constant([[1,2],[3,4],[5]])
r8 = tf.ragged.constant([[7],[],[9,10,11]])
tf.concat([r7,r8],axis=0)

<tf.RaggedTensor [[1, 2], [3, 4], [5], [7], [], [9, 10, 11]]>

In [ ]:
tf.concat([r7,r8],axis=1)

<tf.RaggedTensor [[1, 2, 7], [3, 4], [5, 9, 10, 11]]>

In [ ]:
r8 = tf.ragged.constant([[7],[],[9,10,11],[12,13]])
r8

<tf.RaggedTensor [[7], [], [9, 10, 11], [12, 13]]>

In [ ]:
r8.to_tensor()

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  0,  0],
       [ 0,  0,  0],
       [ 9, 10, 11],
       [12, 13,  0]], dtype=int32)>

In [ ]:
r8.to_tensor(default_value=5)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  5,  5],
       [ 5,  5,  5],
       [ 9, 10, 11],
       [12, 13,  5]], dtype=int32)>

In [ ]:
#sets
import tensorflow as tf
a = tf.constant([[1,5,9]])
b = tf.constant([[5,6,9,11]])
u = tf.sets.union(a,b)
u

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]], shape=(5, 2), dtype=int64), values=tf.Tensor([ 1  5  6  9 11], shape=(5,), dtype=int32), dense_shape=tf.Tensor([1 5], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(u)

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 1,  5,  6,  9, 11]], dtype=int32)>

In [ ]:
#queue
q = tf.queue.FIFOQueue(3,[tf.int32,tf.string],shapes=[(),()])
q.enqueue([10,b"windy"])
q.enqueue([15,b"sunny"])
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
q.dequeue()

[<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'windy'>]

In [ ]:
#multiple records at once using enqueue_many() and dequeue_many()
q.enqueue_many([[13,16],[b'cloudy',b'rainy']])
q.dequeue_many(3)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 13, 16], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'sunny', b'cloudy', b'rainy'], dtype=object)>]